import type { AnalysisResult, FindingCriterion, GapId } from "./types";

const DILLE_URL = "https://www.dille-kamille.nl";
const SOSTRENE_URL = "https://sostrenegrene.com/nl";
const SOSTRENE_PRODUCT_URL = "https://sostrenegrene.com/nl/producten/meubilair/wandrek-p-5b73eb86";

const DILLE_CHECKLISTS: Record<GapId, FindingCriterion[]> = {
  "offer-clarity": [
    { label: "The offer is explicit in the main heading", status: "partial", detail: "The assortment is clear from product collections, while the heading is brand-led." },
    { label: "Representative products or categories are visible", status: "met", detail: "Product collections, cards and prices are visible." },
    { label: "A clear browse, shop or search action is available", status: "met", detail: "Category navigation and assortment links are visible." },
  ],
  "purchase-confidence": [
    { label: "Clear pricing (10%)", status: "met", detail: "Product prices are visible." },
    { label: "Delivery information (15%)", status: "met", detail: "Fast-shipping information is visible." },
    { label: "Returns or refunds (15%)", status: "met", detail: "The 100-day return period is visible." },
    { label: "Reviews or ratings (15%)", status: "met", detail: "Customer ratings are visible." },
    { label: "Payment reassurance (15%)", status: "missing", detail: "Show accepted payment methods near products." },
    { label: "Customer support (10%)", status: "met", detail: "Customer-service details are visible." },
    { label: "Guarantees or certification (10%)", status: "missing", detail: "Show guarantees or certifications near purchase decisions." },
    { label: "Availability (10%)", status: "missing", detail: "Make availability explicit near products." },
  ],
  "customer-journey-path": [
    { label: "A complete route starts on the landing page", status: "met", detail: "A representative route was mapped." },
    { label: "The primary conversion action is detectable", status: "met", detail: "Add to cart is visible on the product page." },
    { label: "The cart and checkout can be mapped", status: "met", detail: "Cart and checkout stages were identified." },
    { label: "3 clicks or fewer to conversion", status: "partial", detail: "The representative route takes 4 clicks." },
  ],
};

const SOSTRENE_CHECKLISTS: Record<GapId, FindingCriterion[]> = {
  "offer-clarity": [
    { label: "The offer is explicit in the main heading", status: "met", detail: "Named collections clarify the assortment." },
    { label: "Representative products or categories are visible", status: "met", detail: "Product cards, collections and prices are visible." },
    { label: "A clear browse, shop or search action is available", status: "met", detail: "Product discovery actions are visible." },
  ],
  "purchase-confidence": [
    { label: "Clear pricing (10%)", status: "met", detail: "Product prices are visible." },
    { label: "Delivery information (15%)", status: "met", detail: "Delivery timing is stated." },
    { label: "Returns or refunds (15%)", status: "met", detail: "Free in-store returns are stated." },
    { label: "Reviews or ratings (15%)", status: "missing", detail: "No visible customer reviews were recorded." },
    { label: "Payment reassurance (15%)", status: "met", detail: "Secure payment methods are shown." },
    { label: "Customer support (10%)", status: "missing", detail: "Direct support details were not recorded near products." },
    { label: "Guarantees or certification (10%)", status: "met", detail: "FSC certification is shown." },
    { label: "Availability (10%)", status: "met", detail: "Stock availability is shown." },
  ],
  "customer-journey-path": [
    { label: "A complete route starts on the landing page", status: "met", detail: "A representative route was mapped." },
    { label: "The primary conversion action is detectable", status: "met", detail: "Add to cart is available on the landing page." },
    { label: "The cart and checkout can be mapped", status: "met", detail: "Cart and checkout stages were identified." },
    { label: "3 clicks or fewer to conversion", status: "met", detail: "The representative route takes 3 clicks." },
  ],
};

export const DEMO_RESULT: AnalysisResult = {
  id: "demo-dille-kamille-2026",
  mode: "fixture",
  url: DILLE_URL,
  companyName: "Dille & Kamille",
  primaryService: "Home, kitchen and lifestyle products",
  score: 86,
  scoreLabel: "Strong foundation",
  confidence: "High",
  analyzedAt: "2026-07-19T13:37:00.000Z",
  summary: "Representative journey score: 86/100 across the three fixed findings.",
  overview: {
    score: 86,
    status: "Strong",
    explanation: "The score summarizes the same three deterministic journey findings.",
    businessModel: "Ecommerce",
    primaryConversion: "Checkout",
    estimatedClicks: 4,
  },
  llmEnhanced: false,
  readiness: {
    status: "scored",
    score: 86,
    assessedWeight: 100,
    minimumWeight: 100,
    formula: "Σ(category score × category weight) ÷ 100",
    categories: [
      {
        id: "offer-clarity",
        label: "Offer Clarity",
        score: 95,
        weight: 35,
        confidence: "High",
        explanation: "The landing page clearly presents home, kitchen and lifestyle products.",
        evidence: [{ statement: "The landing page shows product collections, product cards and prices.", pageLabel: "Dille & Kamille landing page", url: DILLE_URL }],
        checklist: DILLE_CHECKLISTS["offer-clarity"],
        recommendation: "Keep the assortment and category navigation visible together.",
      },
      {
        id: "purchase-confidence",
        label: "Purchase Confidence",
        score: 65,
        weight: 30,
        confidence: "High",
        explanation: "5 of 8 purchase-confidence signals are visible: pricing, delivery, returns, ratings and customer support.",
        evidence: [{ statement: "Saved demo evidence includes product prices, fast shipping, 100-day returns, customer ratings and customer-service details.", pageLabel: "Purchase reassurance", url: DILLE_URL }],
        checklist: DILLE_CHECKLISTS["purchase-confidence"],
        recommendation: "Show accepted payment methods and guarantees near the buying decision.",
      },
      {
        id: "customer-journey-path",
        label: "Customer Journey Path",
        score: 95,
        weight: 35,
        confidence: "High",
        explanation: "The representative route from the landing page to checkout takes four clicks.",
        evidence: [{ statement: "Saved demo path: Homepage → Product → Cart → Checkout (4 clicks).", pageLabel: "Dille & Kamille customer journey", url: DILLE_URL }],
        checklist: DILLE_CHECKLISTS["customer-journey-path"],
        recommendation: "Keep the direct product route and cart access visible.",
      },
    ],
  },
  stats: { pagesCrawled: 5, internalLinks: 482, actionsFound: 48, conversionPathSteps: 4, processingMs: 0 },
  journey: {
    businessModels: ["Ecommerce"],
    primaryOffer: "Home, kitchen and lifestyle products",
    primaryConversionType: "Checkout",
    secondary: [],
    primary: {
      status: "complete",
      name: "Landing page to checkout",
      conversionType: "Checkout",
      startUrl: DILLE_URL,
      destinationUrl: `${DILLE_URL}/checkout`,
      clicksToInterface: 4,
      additionalObservableActions: null,
      shortestRoute: [DILLE_URL, `${DILLE_URL}/product`, `${DILLE_URL}/cart`, `${DILLE_URL}/checkout`],
      alternativeRoute: null,
      confidence: "High",
      limitations: ["This saved demo does not submit a purchase."],
      stages: [
        { order: 1, pageType: "Homepage", title: "Dille & Kamille", url: DILLE_URL, action: "Open a featured product", ctaText: "Bekijk alles", nextStepVisible: true, necessary: true, friction: null },
        { order: 2, pageType: "Product", title: "Product", url: `${DILLE_URL}/product`, action: "Add the product to the cart", ctaText: "In winkelmandje", nextStepVisible: true, necessary: true, friction: null },
        { order: 3, pageType: "Cart", title: "Winkelmandje", url: `${DILLE_URL}/cart`, action: "Open the cart", ctaText: "Winkelmandje", nextStepVisible: true, necessary: true, friction: null },
        { order: 4, pageType: "Checkout", title: "Afrekenen", url: `${DILLE_URL}/checkout`, action: "Continue to checkout", ctaText: "Afrekenen", nextStepVisible: true, necessary: true, friction: null },
      ],
    },
  },
  pages: [
    { title: "Dille & Kamille", url: DILLE_URL, type: "Homepage", statusCode: 200 },
    { title: "Categorie", url: `${DILLE_URL}/categorie`, type: "Category", statusCode: 200 },
    { title: "Product", url: `${DILLE_URL}/product`, type: "Product", statusCode: 200 },
    { title: "Winkelmandje", url: `${DILLE_URL}/cart`, type: "Cart", statusCode: 200 },
    { title: "Afrekenen", url: `${DILLE_URL}/checkout`, type: "Checkout", statusCode: 200 },
  ],
  improvementReport: {
    whatIsDoneWell: [
      "The landing page clearly presents the product range and shopping intent.",
      "The representative route to checkout is short and easy to follow.",
    ],
    whatCouldBeBetter: [
      "Show payment methods and guarantees closer to featured products.",
      "Make purchase reassurance as visible as product discovery.",
    ],
    competitorComparison: [],
  },
  gaps: [
    {
      id: "offer-clarity",
      rank: 1,
      title: "Offer Clarity",
      summary: "The landing page clearly presents home, kitchen and lifestyle products.",
      severity: "Low",
      score: 95,
      confidence: "High",
      evidence: [{ statement: "The landing page shows product collections, product cards and prices.", pageLabel: "Dille & Kamille landing page", url: DILLE_URL }],
      checklist: DILLE_CHECKLISTS["offer-clarity"],
      nextAction: "Keep the assortment and category navigation visible together.",
    },
    {
      id: "purchase-confidence",
      rank: 2,
      title: "Purchase Confidence",
      summary: "5 of 8 purchase-confidence signals are visible: pricing, delivery, returns, ratings and customer support.",
      severity: "Medium",
      score: 65,
      confidence: "High",
      evidence: [{ statement: "Saved demo evidence includes product prices, fast shipping, 100-day returns, customer ratings and customer-service details.", pageLabel: "Purchase reassurance", url: DILLE_URL }],
      checklist: DILLE_CHECKLISTS["purchase-confidence"],
      nextAction: "Show accepted payment methods and guarantees near the buying decision.",
    },
    {
      id: "customer-journey-path",
      rank: 3,
      title: "Customer Journey Path",
      summary: "The representative route from the landing page to checkout takes four clicks.",
      severity: "Low",
      score: 95,
      confidence: "High",
      evidence: [{ statement: "Saved demo path: Homepage → Product → Cart → Checkout (4 clicks).", pageLabel: "Dille & Kamille customer journey", url: DILLE_URL }],
      checklist: DILLE_CHECKLISTS["customer-journey-path"],
      nextAction: "Keep the direct product route and cart access visible.",
    },
  ],
};

export const DEMO_COMPETITOR_RESULT: AnalysisResult = {
  id: "demo-sostrene-grene-2026",
  mode: "fixture",
  url: SOSTRENE_URL,
  companyName: "Søstrene Grene",
  primaryService: "Home, hobby and lifestyle products",
  score: 93,
  scoreLabel: "Strong foundation",
  confidence: "High",
  analyzedAt: "2026-07-19T13:37:00.000Z",
  summary: "Saved competitor comparison across the same three findings.",
  overview: {
    score: 93,
    status: "Strong",
    explanation: "The score summarizes the same three deterministic journey findings.",
    businessModel: "Ecommerce",
    primaryConversion: "Checkout",
    estimatedClicks: 3,
  },
  llmEnhanced: false,
  readiness: {
    status: "scored",
    score: 93,
    assessedWeight: 100,
    minimumWeight: 100,
    formula: "Σ(category score × category weight) ÷ 100",
    categories: [
      {
        id: "offer-clarity",
        label: "Offer Clarity",
        score: 100,
        weight: 35,
        confidence: "High",
        explanation: "The landing page makes it clear that visitors can browse and buy home, hobby and lifestyle products.",
        evidence: [{ statement: "The landing page shows named collections, product cards and prices.", pageLabel: "Søstrene Grene landing page", url: SOSTRENE_URL }],
        checklist: SOSTRENE_CHECKLISTS["offer-clarity"],
        recommendation: "Keep the product range and shopping intent immediately visible.",
      },
      {
        id: "purchase-confidence",
        label: "Purchase Confidence",
        score: 75,
        weight: 30,
        confidence: "High",
        explanation: "6 of 8 purchase-confidence signals are visible: pricing, delivery, returns, payment reassurance, certification and availability.",
        evidence: [{ statement: "Product pages show prices, 1–3 day delivery, free in-store returns, secure payment methods, stock availability and FSC certification.", pageLabel: "Søstrene Grene product reassurance", url: SOSTRENE_PRODUCT_URL }],
        checklist: SOSTRENE_CHECKLISTS["purchase-confidence"],
        recommendation: "Add visible customer reviews and direct support details near products.",
      },
      {
        id: "customer-journey-path",
        label: "Customer Journey Path",
        score: 100,
        weight: 35,
        confidence: "High",
        explanation: "From an empty cart, the landing-page-to-checkout route takes three clicks.",
        evidence: [{ statement: "Saved demo path: Landing-page Add to cart → Cart → Checkout (3 clicks).", pageLabel: "Søstrene Grene customer journey", url: SOSTRENE_URL }],
        checklist: SOSTRENE_CHECKLISTS["customer-journey-path"],
        recommendation: "Keep landing-page Add to cart and cart access visible.",
      },
    ],
  },
  stats: { pagesCrawled: 8, internalLinks: 356, actionsFound: 42, conversionPathSteps: 3, processingMs: 0 },
  journey: {
    businessModels: ["Ecommerce"],
    primaryOffer: "Home, hobby and lifestyle products",
    primaryConversionType: "Checkout",
    secondary: [],
    primary: {
      status: "complete",
      name: "Landing page to checkout",
      conversionType: "Checkout",
      startUrl: SOSTRENE_URL,
      destinationUrl: `${SOSTRENE_URL}/checkout`,
      clicksToInterface: 3,
      additionalObservableActions: null,
      shortestRoute: [SOSTRENE_URL, `${SOSTRENE_URL}/cart`, `${SOSTRENE_URL}/checkout`],
      alternativeRoute: null,
      confidence: "High",
      limitations: ["This saved demo does not submit a purchase."],
      stages: [
        { order: 1, pageType: "Homepage", title: "Søstrene Grene", url: SOSTRENE_URL, action: "Add a featured product to the cart", ctaText: "Add to cart", nextStepVisible: true, necessary: true, friction: null },
        { order: 2, pageType: "Cart", title: "Cart", url: `${SOSTRENE_URL}/cart`, action: "Open the cart", ctaText: "Cart", nextStepVisible: true, necessary: true, friction: null },
        { order: 3, pageType: "Checkout", title: "Checkout", url: `${SOSTRENE_URL}/checkout`, action: "Continue to checkout", ctaText: "Checkout", nextStepVisible: true, necessary: true, friction: null },
      ],
    },
  },
  pages: [
    { title: "Søstrene Grene", url: SOSTRENE_URL, type: "Homepage", statusCode: 200 },
    { title: "Products", url: `${SOSTRENE_URL}/products`, type: "Category", statusCode: 200 },
    { title: "Rooms", url: `${SOSTRENE_URL}/rooms`, type: "Category", statusCode: 200 },
    { title: "New arrivals", url: `${SOSTRENE_URL}/new`, type: "Category", statusCode: 200 },
    { title: "Wandrek", url: SOSTRENE_PRODUCT_URL, type: "Product", statusCode: 200 },
    { title: "Product details", url: `${SOSTRENE_URL}/product/details`, type: "Product", statusCode: 200 },
    { title: "Cart", url: `${SOSTRENE_URL}/cart`, type: "Cart", statusCode: 200 },
    { title: "Checkout", url: `${SOSTRENE_URL}/checkout`, type: "Checkout", statusCode: 200 },
  ],
  improvementReport: {
    whatIsDoneWell: [
      "The landing page makes the assortment immediately clear.",
      "Visitors can add a featured product to the cart without opening its product page first.",
    ],
    whatCouldBeBetter: [
      "Add visible customer reviews and direct support details near products.",
    ],
    competitorComparison: [
      "Søstrene Grene provides more purchase-confidence signals than Dille & Kamille (75% versus 65%).",
      "Its landing-page Add to cart route is one click shorter: three clicks to checkout versus four.",
      "Both websites communicate their product range clearly.",
    ],
  },
  gaps: [
    {
      id: "offer-clarity",
      rank: 1,
      title: "Offer Clarity",
      summary: "The landing page makes it clear that visitors can browse and buy home, hobby and lifestyle products.",
      severity: "Low",
      score: 100,
      confidence: "High",
      evidence: [{ statement: "The landing page shows named collections, product cards and prices.", pageLabel: "Søstrene Grene landing page", url: SOSTRENE_URL }],
      checklist: SOSTRENE_CHECKLISTS["offer-clarity"],
      nextAction: "Keep the product range and shopping intent immediately visible.",
    },
    {
      id: "purchase-confidence",
      rank: 2,
      title: "Purchase Confidence",
      summary: "6 of 8 purchase-confidence signals are visible: pricing, delivery, returns, payment reassurance, certification and availability.",
      severity: "Low",
      score: 75,
      confidence: "High",
      evidence: [{ statement: "Product pages show prices, 1–3 day delivery, free in-store returns, secure payment methods, stock availability and FSC certification.", pageLabel: "Søstrene Grene product reassurance", url: SOSTRENE_PRODUCT_URL }],
      checklist: SOSTRENE_CHECKLISTS["purchase-confidence"],
      nextAction: "Add visible customer reviews and direct support details near products.",
    },
    {
      id: "customer-journey-path",
      rank: 3,
      title: "Customer Journey Path",
      summary: "From an empty cart, the landing-page-to-checkout route takes three clicks.",
      severity: "Low",
      score: 100,
      confidence: "High",
      evidence: [{ statement: "Saved demo path: Landing-page Add to cart → Cart → Checkout (3 clicks).", pageLabel: "Søstrene Grene customer journey", url: SOSTRENE_URL }],
      checklist: SOSTRENE_CHECKLISTS["customer-journey-path"],
      nextAction: "Keep landing-page Add to cart and cart access visible.",
    },
  ],
};
