import type { AnalysisResult, Evidence } from "./types";

const competitorEvidence = (statement: string, url: string): Evidence => ({
  statement,
  pageLabel: "Selected competitor commercial page",
  url,
  source: "competitor",
});

export const DEMO_RESULT: AnalysisResult = {
  id: "demo-noordlicht-2026",
  mode: "fixture",
  url: "https://noordlicht-klimaat.example",
  companyName: "Noordlicht Klimaattechniek",
  primaryService: "Warmtepompinstallatie voor woningen",
  score: 55,
  scoreLabel: "Room to convert",
  confidence: "High",
  analyzedAt: "2026-07-16T09:42:00.000Z",
  summary: "Start with this: shorten the route to a quote.",
  llmEnhanced: false,
  readiness: {
    status: "scored",
    score: 55,
    assessedWeight: 100,
    minimumWeight: 80,
    formula: "Σ(category score × category weight) ÷ Σ(assessed category weights)",
    categories: [
      {
        id: "cta-clarity",
        label: "CTA clarity",
        score: 35,
        weight: 20,
        confidence: "High",
        explanation: "The homepage uses generic prompts instead of a specific buying action.",
        evidence: [{ statement: "Only “Lees meer” and “Contact” were detected as homepage prompts.", pageLabel: "Homepage", url: "https://noordlicht-klimaat.example/" }],
      },
      {
        id: "service-page-coverage",
        label: "Service-page coverage",
        score: 58,
        weight: 20,
        confidence: "High",
        explanation: "Only one dedicated service page was visible in the bounded crawl.",
        evidence: [{ statement: "One dedicated service page was detected across seven crawled pages.", pageLabel: "Services overview", url: "https://noordlicht-klimaat.example/diensten" }],
      },
      {
        id: "conversion-path-quality",
        label: "Conversion-path quality",
        score: 30,
        weight: 20,
        confidence: "High",
        explanation: "The shortest visible quote route takes three clicks.",
        evidence: [{ statement: "Homepage → Diensten → Contact → Form.", pageLabel: "Detected conversion route", url: "https://noordlicht-klimaat.example/contact" }],
      },
      {
        id: "form-friction",
        label: "Form friction",
        score: 92,
        weight: 15,
        confidence: "High",
        explanation: "The detected form asks for relatively little information.",
        evidence: [{ statement: "The quote form contains four visible fields; three appear required.", pageLabel: "Contact page", url: "https://noordlicht-klimaat.example/contact" }],
      },
      {
        id: "message-consistency",
        label: "Message consistency",
        score: 100,
        weight: 10,
        confidence: "High",
        explanation: "The main warmtepomp message is repeated consistently.",
        evidence: [{ statement: "Main service terms appear in all four comparable headings and descriptions.", pageLabel: "Homepage and service-page copy", url: "https://noordlicht-klimaat.example/" }],
      },
      {
        id: "trust-signals",
        label: "Trust signals",
        score: 45,
        weight: 15,
        confidence: "High",
        explanation: "Some proof exists elsewhere, but none is visible beside the quote form.",
        evidence: [{ statement: "No review, certification, case-study, guarantee or contact-detail evidence is visible beside the quote form.", pageLabel: "Contact page", url: "https://noordlicht-klimaat.example/contact" }],
      },
    ],
  },
  stats: {
    pagesCrawled: 7,
    internalLinks: 34,
    ctasFound: 2,
    formsFound: 1,
    formFields: 4,
    servicePages: 1,
    trustSignals: 3,
    conversionPathSteps: 3,
    processingMs: 6840,
  },
  market: { geography: "Utrecht", targetCustomer: "particulieren" },
  competitors: {
    status: "available",
    label: "Likely public search competitors",
    query: "warmtepompinstallatie woningen Utrecht particulieren",
    geography: "Utrecht",
    targetCustomer: "particulieren",
    entity: {
      companyName: "Noordlicht Klimaattechniek",
      domain: "noordlicht-klimaat.example",
      industry: "HVAC and climate installation",
      businessModel: "local-service",
      offerings: ["Warmtepompinstallatie", "Warmtepompadvies"],
      geography: "Utrecht",
      targetCustomer: "particulieren",
      confidence: "High",
      method: "openrouter",
    },
    note: "Resolved Noordlicht Klimaattechniek as HVAC and climate installation, then selected matching Dutch public-search businesses with the same market profile. Only one commercial page per domain was checked.",
    competitors: [
      {
        name: "Rijnstad Warmtepompen",
        url: "https://rijnstad-warmte.example/warmtepomp-installatie",
        pageTitle: "Warmtepomp laten installeren | Rijnstad",
        label: "Likely public search competitor",
        dedicatedServicePage: true,
        ctaClarity: 92,
        conversionPathSteps: 0,
        trustSignals: ["Reviews or ratings", "Certifications", "Guarantees"],
        metrics: [
          { label: "Dedicated service page", value: "Visible", evidence: competitorEvidence("The selected result is a service-specific commercial page.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
          { label: "CTA clarity", value: "92/100", evidence: competitorEvidence("The selected page uses the CTA “Vraag een gratis adviesgesprek aan”.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
          { label: "Direct conversion path", value: "Form on page", evidence: competitorEvidence("A short enquiry form is visible on the selected page.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
          { label: "Trust signals", value: "3 types", evidence: competitorEvidence("Reviews, a certification and an installation guarantee are visible.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
        ],
      },
      {
        name: "EcoWarm Utrecht",
        url: "https://ecowarm-utrecht.example/diensten/warmtepompen",
        pageTitle: "Warmtepompen voor woningen | EcoWarm Utrecht",
        label: "Likely public search competitor",
        dedicatedServicePage: true,
        ctaClarity: 72,
        conversionPathSteps: 1,
        trustSignals: ["Testimonials", "Contact details"],
        metrics: [
          { label: "Dedicated service page", value: "Visible", evidence: competitorEvidence("The selected result is a service-specific commercial page.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
          { label: "CTA clarity", value: "72/100", evidence: competitorEvidence("The selected page uses the CTA “Plan een adviesgesprek”.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
          { label: "Direct conversion path", value: "1 step", evidence: competitorEvidence("The selected page links directly to its contact page.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
          { label: "Trust signals", value: "2 types", evidence: competitorEvidence("A testimonial and clear contact details are visible.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
        ],
      },
    ],
  },
  journey: {
    businessModels: ["Lead generation", "Local service business"],
    primaryOffer: "Warmtepompinstallatie voor woningen",
    primaryConversionType: "Quote request",
    primary: {
      name: "Quote request journey",
      conversionType: "Quote request",
      startUrl: "https://noordlicht-klimaat.example/",
      destinationUrl: "https://noordlicht-klimaat.example/contact",
      clicksToInterface: 3,
      additionalObservableActions: 4,
      shortestRoute: [
        "https://noordlicht-klimaat.example/",
        "https://noordlicht-klimaat.example/diensten",
        "https://noordlicht-klimaat.example/contact",
        "https://noordlicht-klimaat.example/contact#form",
      ],
      alternativeRoute: null,
      confidence: "High",
      limitations: [
        "No purchase, account creation or form submission was completed.",
        "Dynamic, personalized, logged-in and payment steps may not be visible in public HTML.",
        "The detected shortest path may differ from routes used by real visitors.",
      ],
      stages: [
        { order: 1, pageType: "Homepage", title: "Noordlicht Klimaattechniek", url: "https://noordlicht-klimaat.example/", action: "Click “Diensten”", ctaText: "Diensten", nextStepVisible: true, necessary: true, friction: "The route does not start with a direct quote action." },
        { order: 2, pageType: "Service", title: "Onze diensten", url: "https://noordlicht-klimaat.example/diensten", action: "Click “Contact”", ctaText: "Contact", nextStepVisible: true, necessary: true, friction: "The route uses a generic contact action." },
        { order: 3, pageType: "Contact", title: "Contact", url: "https://noordlicht-klimaat.example/contact", action: "Open the quote form", ctaText: "Vraag offerte aan", nextStepVisible: true, necessary: true, friction: null },
        { order: 4, pageType: "Quote", title: "Offerteformulier", url: "https://noordlicht-klimaat.example/contact#form", action: "Reach the quote request interface", ctaText: null, nextStepVisible: true, necessary: true, friction: null },
      ],
    },
    secondary: [],
  },
  pages: [
    { title: "Noordlicht Klimaattechniek", url: "https://noordlicht-klimaat.example/", type: "Homepage", statusCode: 200 },
    { title: "Onze diensten", url: "https://noordlicht-klimaat.example/diensten", type: "Service", statusCode: 200 },
    { title: "Over Noordlicht", url: "https://noordlicht-klimaat.example/over-ons", type: "Other", statusCode: 200 },
    { title: "Projecten", url: "https://noordlicht-klimaat.example/projecten", type: "Other", statusCode: 200 },
    { title: "Subsidies", url: "https://noordlicht-klimaat.example/subsidies", type: "Other", statusCode: 200 },
    { title: "Veelgestelde vragen", url: "https://noordlicht-klimaat.example/vragen", type: "Other", statusCode: 200 },
    { title: "Contact", url: "https://noordlicht-klimaat.example/contact", type: "Contact", statusCode: 200 },
  ],
  gaps: [
    {
      id: "conversion-path",
      rank: 1,
      title: "Quote path may lose visitors",
      summary: "The shortest visible route to the quote form takes three clicks.",
      severity: "High",
      score: 70,
      confidence: "High",
      evidence: [
        { statement: "Homepage → Diensten → Contact → Form.", pageLabel: "Detected conversion route", url: "https://noordlicht-klimaat.example/contact" },
        competitorEvidence("Likely public search competitor Rijnstad Warmtepompen exposes a form on its selected commercial page.", "https://rijnstad-warmte.example/warmtepomp-installatie"),
      ],
      nextAction: "Link the homepage CTA directly to the quote form.",
    },
    {
      id: "cta",
      rank: 2,
      title: "Primary CTA may be unclear",
      summary: "The homepage uses generic prompts instead of a specific next step.",
      severity: "High",
      score: 65,
      confidence: "High",
      evidence: [
        { statement: "Only “Lees meer” and “Contact” were detected as homepage prompts.", pageLabel: "Homepage", url: "https://noordlicht-klimaat.example/" },
        competitorEvidence("Likely public search competitor Rijnstad Warmtepompen uses “Vraag een gratis adviesgesprek aan”.", "https://rijnstad-warmte.example/warmtepomp-installatie"),
      ],
      nextAction: "Use “Vraag warmteadvies aan” as the primary CTA.",
    },
    {
      id: "trust-signals",
      rank: 3,
      title: "Quote form lacks visible proof",
      summary: "Relevant proof exists elsewhere but not beside the quote form.",
      severity: "Medium",
      score: 55,
      confidence: "High",
      evidence: [
        { statement: "No configured trust-signal type is visible beside the quote form.", pageLabel: "Contact page", url: "https://noordlicht-klimaat.example/contact" },
        competitorEvidence("Likely public search competitor Rijnstad Warmtepompen shows reviews, certification and a guarantee on its selected page.", "https://rijnstad-warmte.example/warmtepomp-installatie"),
      ],
      nextAction: "Add a review, certification and guarantee beside the form.",
    },
  ],
};
