import type { AnalysisResult, Evidence } from "./types";

const competitorEvidence = (statement: string, url: string): Evidence => ({
  statement,
  pageLabel: "Selected competitor commercial page",
  url,
  source: "competitor",
});

export const DEMO_RESULT: AnalysisResult = {
  id: "demo-noordlicht-2026",
  mode: "fixture",
  url: "https://noordlicht-klimaat.example",
  companyName: "Noordlicht Klimaattechniek",
  primaryService: "Warmtepompinstallatie voor woningen",
  score: 58,
  scoreLabel: "Room to convert",
  confidence: "High",
  analyzedAt: "2026-07-16T09:42:00.000Z",
  summary: "Representative journey score: 58/100 across offer clarity, CTA clarity and customer journey path.",
  overview: {
    score: 58,
    status: "Needs attention",
    explanation: "The representative journey contains visible acquisition friction.",
    businessModel: "Local service business",
    primaryConversion: "Quote request",
    estimatedClicks: 3,
  },
  llmEnhanced: false,
  readiness: {
    status: "scored",
    score: 58,
    assessedWeight: 100,
    minimumWeight: 100,
    formula: "Σ(category score × category weight) ÷ Σ(assessed category weights)",
    categories: [
      { id: "offer-clarity", label: "Offer Clarity", score: 78, weight: 35, confidence: "High", explanation: "The landing page states the heat-pump offer, but the outcome could be more immediate.", evidence: [{ statement: "The title and main heading identify residential heat-pump installation.", pageLabel: "Homepage", url: "https://noordlicht-klimaat.example/" }] },
      { id: "cta-clarity", label: "CTA Clarity", score: 35, weight: 30, confidence: "High", explanation: "The homepage uses generic prompts instead of a specific buying action.", evidence: [{ statement: "Only “Lees meer” and “Contact” were detected as homepage prompts.", pageLabel: "Homepage", url: "https://noordlicht-klimaat.example/" }] },
      { id: "customer-journey-path", label: "Customer Journey Path", score: 55, weight: 35, confidence: "High", explanation: "The shortest visible quote route takes three clicks.", evidence: [{ statement: "Homepage → Diensten → Contact → Form.", pageLabel: "Detected conversion route", url: "https://noordlicht-klimaat.example/contact" }] },
    ],
  },
  stats: {
    pagesCrawled: 7,
    internalLinks: 34,
    ctasFound: 2,
    formsFound: 1,
    formFields: 4,
    servicePages: 1,
    trustSignals: 3,
    conversionPathSteps: 3,
    processingMs: 6840,
  },
  market: { geography: "Utrecht", targetCustomer: "particulieren" },
  competitors: {
    status: "available",
    label: "Likely public search competitors",
    query: "warmtepompinstallatie woningen Utrecht particulieren",
    geography: "Utrecht",
    targetCustomer: "particulieren",
    entity: {
      companyName: "Noordlicht Klimaattechniek",
      domain: "noordlicht-klimaat.example",
      industry: "HVAC and climate installation",
      businessModel: "local-service",
      offerings: ["Warmtepompinstallatie", "Warmtepompadvies"],
      geography: "Utrecht",
      targetCustomer: "particulieren",
      confidence: "High",
      method: "openrouter",
    },
    note: "Resolved Noordlicht Klimaattechniek as HVAC and climate installation, then selected matching Dutch public-search businesses with the same market profile. Only one commercial page per domain was checked.",
    competitors: [
      {
        name: "Rijnstad Warmtepompen",
        url: "https://rijnstad-warmte.example/warmtepomp-installatie",
        pageTitle: "Warmtepomp laten installeren | Rijnstad",
        label: "Likely public search competitor",
        dedicatedServicePage: true,
        ctaClarity: 92,
        conversionPathSteps: 0,
        trustSignals: ["Reviews or ratings", "Certifications", "Guarantees"],
        findings: [
          { id: "offer-clarity", rank: 1, title: "Offer Clarity", summary: "The selected page clearly describes residential heat-pump installation.", severity: "Low", score: 92, confidence: "Medium", evidence: [competitorEvidence("The page title, heading and description repeat the installation offer.", "https://rijnstad-warmte.example/warmtepomp-installatie")], nextAction: "Keep the offer consistent." },
          { id: "cta-clarity", rank: 2, title: "CTA Clarity", summary: "A specific advice CTA is visible on the selected page.", severity: "Low", score: 92, confidence: "Medium", evidence: [competitorEvidence("The selected page uses “Vraag een gratis adviesgesprek aan”.", "https://rijnstad-warmte.example/warmtepomp-installatie")], nextAction: "Keep the CTA consistent." },
          { id: "customer-journey-path", rank: 3, title: "Customer Journey Path", summary: "A conversion form is visible on the selected page.", severity: "Low", score: 95, confidence: "Medium", evidence: [competitorEvidence("A short enquiry form is visible on the selected page.", "https://rijnstad-warmte.example/warmtepomp-installatie")], nextAction: "Keep the route prominent." },
        ],
        metrics: [
          { label: "Dedicated service page", value: "Visible", evidence: competitorEvidence("The selected result is a service-specific commercial page.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
          { label: "CTA clarity", value: "92/100", evidence: competitorEvidence("The selected page uses the CTA “Vraag een gratis adviesgesprek aan”.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
          { label: "Direct conversion path", value: "Form on page", evidence: competitorEvidence("A short enquiry form is visible on the selected page.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
          { label: "Trust signals", value: "3 types", evidence: competitorEvidence("Reviews, a certification and an installation guarantee are visible.", "https://rijnstad-warmte.example/warmtepomp-installatie") },
        ],
      },
      {
        name: "EcoWarm Utrecht",
        url: "https://ecowarm-utrecht.example/diensten/warmtepompen",
        pageTitle: "Warmtepompen voor woningen | EcoWarm Utrecht",
        label: "Likely public search competitor",
        dedicatedServicePage: true,
        ctaClarity: 72,
        conversionPathSteps: 1,
        trustSignals: ["Testimonials", "Contact details"],
        findings: [
          { id: "offer-clarity", rank: 1, title: "Offer Clarity", summary: "The selected page clearly presents its heat-pump service.", severity: "Low", score: 86, confidence: "Medium", evidence: [competitorEvidence("The page title and heading identify heat pumps for homes.", "https://ecowarm-utrecht.example/diensten/warmtepompen")], nextAction: "Keep the offer consistent." },
          { id: "cta-clarity", rank: 2, title: "CTA Clarity", summary: "A specific consultation CTA is visible.", severity: "Low", score: 72, confidence: "Medium", evidence: [competitorEvidence("The selected page uses “Plan een adviesgesprek”.", "https://ecowarm-utrecht.example/diensten/warmtepompen")], nextAction: "Keep one CTA label." },
          { id: "customer-journey-path", rank: 3, title: "Customer Journey Path", summary: "The selected page exposes a one-click contact route.", severity: "Low", score: 80, confidence: "Medium", evidence: [competitorEvidence("The selected page links directly to its contact page.", "https://ecowarm-utrecht.example/diensten/warmtepompen")], nextAction: "Keep the route prominent." },
        ],
        metrics: [
          { label: "Dedicated service page", value: "Visible", evidence: competitorEvidence("The selected result is a service-specific commercial page.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
          { label: "CTA clarity", value: "72/100", evidence: competitorEvidence("The selected page uses the CTA “Plan een adviesgesprek”.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
          { label: "Direct conversion path", value: "1 step", evidence: competitorEvidence("The selected page links directly to its contact page.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
          { label: "Trust signals", value: "2 types", evidence: competitorEvidence("A testimonial and clear contact details are visible.", "https://ecowarm-utrecht.example/diensten/warmtepompen") },
        ],
      },
    ],
  },
  journey: {
    businessModels: ["Lead generation", "Local service business"],
    primaryOffer: "Warmtepompinstallatie voor woningen",
    primaryConversionType: "Quote request",
    primary: {
      name: "Quote request journey",
      conversionType: "Quote request",
      startUrl: "https://noordlicht-klimaat.example/",
      destinationUrl: "https://noordlicht-klimaat.example/contact",
      clicksToInterface: 3,
      additionalObservableActions: 4,
      shortestRoute: [
        "https://noordlicht-klimaat.example/",
        "https://noordlicht-klimaat.example/diensten",
        "https://noordlicht-klimaat.example/contact",
        "https://noordlicht-klimaat.example/contact#form",
      ],
      alternativeRoute: null,
      confidence: "High",
      limitations: [
        "No purchase, account creation or form submission was completed.",
        "Dynamic, personalized, logged-in and payment steps may not be visible in public HTML.",
        "The detected shortest path may differ from routes used by real visitors.",
      ],
      stages: [
        { order: 1, pageType: "Homepage", title: "Noordlicht Klimaattechniek", url: "https://noordlicht-klimaat.example/", action: "Click “Diensten”", ctaText: "Diensten", nextStepVisible: true, necessary: true, friction: "The route does not start with a direct quote action." },
        { order: 2, pageType: "Service", title: "Onze diensten", url: "https://noordlicht-klimaat.example/diensten", action: "Click “Contact”", ctaText: "Contact", nextStepVisible: true, necessary: true, friction: "The route uses a generic contact action." },
        { order: 3, pageType: "Contact", title: "Contact", url: "https://noordlicht-klimaat.example/contact", action: "Open the quote form", ctaText: "Vraag offerte aan", nextStepVisible: true, necessary: true, friction: null },
        { order: 4, pageType: "Quote", title: "Offerteformulier", url: "https://noordlicht-klimaat.example/contact#form", action: "Reach the quote request interface", ctaText: null, nextStepVisible: true, necessary: true, friction: null },
      ],
    },
    secondary: [],
  },
  pages: [
    { title: "Noordlicht Klimaattechniek", url: "https://noordlicht-klimaat.example/", type: "Homepage", statusCode: 200 },
    { title: "Onze diensten", url: "https://noordlicht-klimaat.example/diensten", type: "Service", statusCode: 200 },
    { title: "Over Noordlicht", url: "https://noordlicht-klimaat.example/over-ons", type: "Other", statusCode: 200 },
    { title: "Projecten", url: "https://noordlicht-klimaat.example/projecten", type: "Other", statusCode: 200 },
    { title: "Subsidies", url: "https://noordlicht-klimaat.example/subsidies", type: "Other", statusCode: 200 },
    { title: "Veelgestelde vragen", url: "https://noordlicht-klimaat.example/vragen", type: "Other", statusCode: 200 },
    { title: "Contact", url: "https://noordlicht-klimaat.example/contact", type: "Contact", statusCode: 200 },
  ],
  gaps: [
    {
      id: "offer-clarity",
      rank: 1,
      title: "Offer Clarity",
      summary: "The heat-pump offer is visible, but its customer outcome could be stated faster.",
      severity: "Medium",
      score: 78,
      confidence: "High",
      evidence: [
        { statement: "The title and main heading identify residential heat-pump installation.", pageLabel: "Homepage", url: "https://noordlicht-klimaat.example/" },
        competitorEvidence("Likely public search competitor Rijnstad Warmtepompen scores 92/100 for Offer Clarity.", "https://rijnstad-warmte.example/warmtepomp-installatie"),
      ],
      nextAction: "State the customer outcome in the main heading.",
    },
    {
      id: "cta-clarity",
      rank: 2,
      title: "CTA Clarity",
      summary: "The homepage uses generic prompts instead of one specific conversion action.",
      severity: "High",
      score: 35,
      confidence: "High",
      evidence: [
        { statement: "Only “Lees meer” and “Contact” were detected as homepage prompts.", pageLabel: "Homepage", url: "https://noordlicht-klimaat.example/" },
        competitorEvidence("Likely public search competitor Rijnstad Warmtepompen uses “Vraag een gratis adviesgesprek aan”.", "https://rijnstad-warmte.example/warmtepomp-installatie"),
      ],
      nextAction: "Use “Vraag warmteadvies aan” as the primary CTA.",
    },
    {
      id: "customer-journey-path",
      rank: 3,
      title: "Customer Journey Path",
      summary: "The shortest evidenced route reaches the quote form in three clicks.",
      severity: "Medium",
      score: 55,
      confidence: "High",
      evidence: [
        { statement: "Homepage → Diensten → Contact → Form.", pageLabel: "Detected conversion route", url: "https://noordlicht-klimaat.example/contact" },
        competitorEvidence("Likely public search competitor Rijnstad Warmtepompen exposes a conversion form on its selected page.", "https://rijnstad-warmte.example/warmtepomp-installatie"),
      ],
      nextAction: "Link the homepage CTA directly to the quote form.",
    },
  ],
};
